vich_uploader:
  db_driver: orm
  mappings:
    blog:
      uri_prefix: /img/articles
      upload_destination: "%kernel.project_dir%/public/img/blog"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
